### ISSUE TITLE
Front Page Requests

### ISSUE THREAD

**Issue by EEslacker** [akosborn/umspreadsheet_server#5]
![image](https://cloud.githubusercontent.com/assets/27736500/25196841/e336418c-250f-11e7-90d3-8eb2f4c5127d.png)

**Comment by akosborn** [comment]
This is the most the space can be decreased between the logo and the header because the image dimensions are a little larger than the extent of the actual logo. Thoughts on the font-size update? This is the font that's only caps, so this is the only option unless we change the font altogether.

![fixed](https://cloud.githubusercontent.com/assets/20467592/25257523/248ff288-25fe-11e7-8cf8-6a8708781ae6.PNG)

**Comment by akosborn** [comment]
![fixed](https://cloud.githubusercontent.com/assets/20467592/25261600/4f2bd56a-2618-11e7-9db5-bdfb08a1ce81.PNG)

**Comment by EEslacker** [comment]
All of this looks Great! just one thing, in the blurb on Front Page, "UMSpreadsheet" should be "UMspreadsheet"

**Comment by akosborn** [comment]
![fixed](https://cloud.githubusercontent.com/assets/20467592/25292295/23c8aba4-269b-11e7-9cfb-932b925f6ada.PNG)

Front page should be good to go for now, so gonna' close this one
